### ISSUE TITLE
Prefixes

### ISSUE THREAD

**Issue by TDMidkwhatisxd** [Johnmacrocraft/NotMeXboxLiveAuth#3]
What if you can set to allow  name prefixes .... I mean any player with names guest_ prefix should be allowed to enter without xbox ... Example Guest_Steve

**Comment by Johnmacrocraft** [comment]
Good idea, but what if someone with the prefix connects to server but wants to authenticate with Xbox Live? It would be a pain... (In that case it won't be a problem because afaik underscores aren't allowed in Xbox Live gamertag, but for other cases it could be)
~~_Edit: Apparently this isn't a problem because players can still authenticate with the prefix, my bad. Why on the earth did I think like that >___<_~~
_Edit: (Once again) Actually a problem because other players can connect with accounts starting with prefix even they're not owner of them, workaround would be adding an option for players to use Xbox Live Auth or not; still thinking of other ways for this problem._

**Comment by TDMidkwhatisxd** [comment]
But what if you add a config to choose our prefix, if a player claim that prefix to xbox so be it, he knew it was a guest prefix... Or else u can change name to players that are not on xbox, like Guest38855855, and so on. It would be nice to allow non xbox players...

**Comment by TDMidkwhatisxd** [comment]
You can add a built in auth system, just a small one, like set a pin with max attempts ...
+ These are guest usernames so nobody cares if all can use that username with prefix.
edit: auth system should be on for non xbox players only ...

**Comment by Johnmacrocraft** [comment]
Implemented in 06427a19b3081fce6a8e84ad7ec563a318ca92af. Note that authentication wasn't added because I thought it's not something this plugin should do.
